name: jp_study_app
description: Offline Japanese SRS study app (local sqlite + local media)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # DB + paths
  sqflite: ^2.3.3
  path_provider: ^2.1.4

  # Import DB (picker optional)
  file_picker: ^8.1.2

  # Permissions (All files access for local media folders)
  permission_handler: ^11.3.1

  # Persist settings
  shared_preferences: ^2.3.2

  # Audio
  just_audio: ^0.9.39

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
